<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <?=$this->headTitle('IdentityOnly')->setSeparator(' - ')->setAutoEscape(false)?>
        
        <?=$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')?>
        
        <?=$this->headLink(array(
            'rel' => 'shortcut icon',
            'type' => 'image/png',
            'href' => $this->basePath().'/images/favicon.png',
        ))?>
        
    </head>
    <body>
        <div class="content">
            <div class="header">
            
            </div>
            <div class="inner-content">
                <?php echo $this->content; ?>
            </div>
            <div class="footer">
            
            </div>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
